version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01 #Ubuntu 16.04, docker 19.03.8, docker-compose 1.25.5
      docker_layer_caching: true
    working_directory: ~/project
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Install Packages
        command: |
          sudo rm -rf /opt/circleci/.nvm
          sudo apt-get update
          sudo apt-get install -y git python make gcc g++ bash curl
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt-get install -y nodejs
    - run:
        name: npm version
        command: npm -v
    - run:
        name: install-npm
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules
    - run:
        name: test
        command: npm test

workflows:
  version: 2
  workflow:
    jobs:
    - build
