version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
    - image: circleci/node:12.9.0-stretch
    steps:
    - checkout
#    - restore_cache:
#        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: install-npm
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules
    - setup_remote_docker
    - run:
        name: test
        command: npm test
workflows:
  version: 2
  workflow:
    jobs:
    - build

