---
version: 2.1

executors:
  node_executor:
    docker:
      - image: circleci/node:12.9.0-stretch

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01 #Ubuntu 16.04, docker 19.03.8, docker-compose 1.25.5
      docker_layer_caching: true
    working_directory: ~/project
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Install Packages
        command: |
          sudo rm -rf /opt/circleci/.nvm
          sudo apt-get update
          sudo apt-get install -y git python make gcc g++ bash curl
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt-get install -y nodejs
    - run:
        name: npm version
        command: npm -v
    - run:
        name: install-npm
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules
    - run:
        name: test
        command: npm test

  publishDoc:
    executor: node_executor
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: install-npm
        command: npm install
    - save_cache:
        paths:
          - ./node_modules
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: build doc
        command: npm run generate-docs
    - add_ssh_keys:
        fingerprints:
          - 'b4:b3:84:2a:8d:25:45:39:f4:b1:86:4d:d4:db:fb:b4'
    - run:
        name: Set Git user params
        command: |
          git config --global user.name $CIRCLE_USERNAME
          git config --global user.email "${CIRCLE_USERNAME}@users.noreply.github.com"
    - deploy:
        name: Commit and push docs changes
        command: |
          git add docs/*
          git commit -m "Automated SDK documentation update" \
                     -m "[skip ci] Circle CI build ${CIRCLE_BUILD_NUM}, see ${CIRCLE_BUILD_URL}" \
                     -m "Branch: ${CIRCLE_BRANCH}, commit: ${CIRCLE_SHA1}, tag:${CIRCLE_TAG-none}"
          git push --set-upstream origin ${CIRCLE_BRANCH}
          git push origin

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - publishDoc #:
        requires:
          - build
        filters:
          branches:
            only: master
