version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/project
    steps:
    - checkout
#    - restore_cache:
#        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: Install Packages
        command: |
          sudo apt update
          sudo apt install -y git nodejs npm python make gcc g++ bash docker-compose curl
    - run:
        name: install-npm
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules
    - run:
        name: test
        command: npm test
workflows:
  version: 2
  workflow:
    jobs:
    - build

